# name: Hello world workflow

# on:
#   push:
#   pull_request:
#   workflow_dispatch:

# jobs:
#   hello:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: hello world
#         run: echo "Hello World"
#         shell: bash
#   goodbye:
#     runs-on: ubuntu-latest
#     steps:
#       - name: goodbye world
#         run: echo "Goodbye World"
#         shell: bash

