name: Update Lint Branch

on:
  push:
    branches: [main]

permissions: write-all

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git User
        run: |
          git config user.name "GitHub Action"
          git config user.email "thurairaj.l@setel.com"

      - name: Update Lint Branch
        run: |
          git checkout main
          git fetch origin
          git checkout feature/lint
          git pull
          git merge origin/main
          git push origin feature/lint
